version: '3.8'

services:
  voteappapiimg:
    build:
      context: VoteAppApi
      dockerfile: deploy/DockerfileApi
    container_name: voteappapi
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=prod
    command: ["dotnet", "VoteApi.Api.dll", "--launch-profile", "Docker"]
    volumes:
      - ./docker/api/logs:/app/Logs
    depends_on:
      - databaseimg

  voteappimg:
    build:
      context: VoteApp
      dockerfile: deploy/DockerfileUI
    container_name: voteapp
    ports:
      - "4200:80"
    depends_on:
      - voteappapiimg

  databaseimg:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: voteappdb
    environment:
      - SA_PASSWORD=abcDEF123#
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - ./docker/db/data:/var/opt/mssql/data
      - ./docker/db/log:/var/opt/mssql/log
      - ./docker/db/secrets:/var/opt/mssql/secrets
